name: Sync Labels

permissions:
  contents: write
  pull-requests: write

on:
  push:
    paths:
      - '.github/labels.json'
  workflow_dispatch: # manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync Labels
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels-file: .github/labels.json
          branch: label-sync
          title: 'Sync labels from labels.json'
          body: 'This PR updates the labels based on the latest labels.json file.'
          committer: 'GitHub Actions <actions@github.com>'
          author: 'GitHub Actions <actions@github.com>'
          paths: |
            .github/labels.json
