name: Sync Labels

on:
  push:
    paths:
      - '.github/labels.json'
  workflow_dispatch: # manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync Labels
        uses: peter-evans/create-or-update-label@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          labels-file: .github/labels.json
